### ISSUE TITLE
Improve performance of remapping

### ISSUE THREAD

**Issue by peterrum** [hpsint/hpsint#500]
Here some scaling of the initial remapping phase (up to 1k particles):

![Screenshot from 2023-03-08 14-07-15](https://user-images.githubusercontent.com/15707929/223721288-e61aefc4-3619-483a-a69b-b29e7c422364.png)

We need to work on this, #478 and #482 have been reverted. Also I don't understand why the initial order parameter assignment are not good? @vovannikov I thought you have fixed that!?

**Comment by vovannikov** [comment]
Could you check if #503 helped?

**Comment by vovannikov** [comment]
Also, if here the settings from this comment https://github.com/hpsint/hpsint/issues/497#issuecomment-1479584318 were used, then it explains why you still get the initial remappings. In those files `"InterfaceBufferRatio": "1",` whereas I changed it in the updated versions from 4ea822decb61aa014a8bd5761df2f3aa2830e259.

**Comment by peterrum** [comment]
> Also, if here the settings from this comment https://github.com/hpsint/hpsint/issues/497#issuecomment-1479584318 were used, then it explains why you still get the initial remappings. In those files "InterfaceBufferRatio": "1", whereas I changed it in the updated versions from https://github.com/hpsint/hpsint/commit/4ea822decb61aa014a8bd5761df2f3aa2830e259.

I am aware of that. I kept the old setting to be able to compare the performance of the old and new algo fairly.

**Comment by vovannikov** [comment]
I suppose we can close this with #503? What do you think @peterrum.
